name: flutter_firebase_ui
description: Firebase auth UI, dart package try to mimic the firebaseUI.
version: 0.0.11
author: Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=1.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.5.7

  google_sign_in: "^3.0.3+1"
  flutter_facebook_login: "^1.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
   - assets/fb-logo.png
   - assets/2.0x/fb-logo.png
   - assets/3.0x/fb-logo.png

   - assets/email-logo.png
   - assets/2.0x/email-logo.png
   - assets/3.0x/email-logo.png

   - assets/go-logo.png
   - assets/2.0x/go-logo.png
   - assets/3.0x/go-logo.png
