name: flutter_firebase_ui
description: Firebase auth UI, dart package try to mimic the firebaseUI.
version: 0.0.2
author: Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/fidelisa/flutter_plugins

environment:
  sdk: ">=1.8.0 <2.1.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: "^2.1.0"
  flutter_facebook_login: "^1.0.3"
  firebase_auth: "^0.5.0"

dev_dependencies:
  test: ^0.12.0
  flutter_test:
    sdk: flutter


flutter:
  assets:
   - assets/fb-logo.png
   - assets/2.0x/fb-logo.png
   - assets/3.0x/fb-logo.png

   - assets/email-logo.png
   - assets/2.0x/email-logo.png
   - assets/3.0x/email-logo.png

   - assets/go-logo.png
   - assets/2.0x/go-logo.png
   - assets/3.0x/go-logo.png
